# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
ENV['VAGRANT_SERVER_URL'] = 'http://vagrant.elab.pro'
#Vagrant.configure("2") do |config|
#  config.vm.box = "ubuntu/20.04"
# Описываем Виртуальные машины
MACHINES = {
  # Указываем имя ВМ "kernel update"
  :"mdadm" => {
              #Какой vm box будем использовать
              :box_name => "centos/8",
              #Указываем box_version
              :box_version => "1.0.0",
              #Указываем количество ядер ВМ
              :cpus => 2,
              #Указываем количество ОЗУ в мегабайтах
              :memory => 1024,
          }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    # Отключаем проброс общей папки в ВМ
    config.vm.synced_folder ".", "/vagrant", disabled: true
    # Применяем конфигурацию ВМ
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
        v.customize ["storagectl", :id, "--name", "SATA Controller", "--add", "sata"]
      (1..5).each do |i|
        v.customize ["createhd", "--filename", "/tmp/disk#{i}.vdi", "--size", "1024"]
        v.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", "#{i}", "--device", "0", "--type", "hdd", "--medium", "/tmp/disk#{i}.vdi"]
      end
      end
    end
  end
end