# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
ENV['VAGRANT_SERVER_URL'] = 'http://vagrant.elab.pro'
#Vagrant.configure("2") do |config|
#  config.vm.box = "ubuntu/20.04"
# Описываем Виртуальные машины
MACHINES = {
  # Указываем имя ВМ "kernel update"
  :"Systemd" => {
              #Какой vm box будем использовать
              :box_name => "ubuntu/jammy64",
              #Указываем box_version
              :box_version => "1.0.0",
              #Указываем количество ядер ВМ
              :cpus => 2,
              #Указываем количество ОЗУ в мегабайтах
              :memory => 1024,
          }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    # Отключаем проброс общей папки в ВМ
    config.vm.synced_folder ".", "/vagrant", disabled: true
    # Применяем конфигурацию ВМ
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s
      box.vm.disk :disk, size: "10GB", primary: true
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end
#      box.vm.provision "file", source: "./script", destination: "/tmp"
#      box.vm.provision "shell", inline: <<-SHELL
#        mkdir -p ~root/.ssh
#        cp ~vagrant/.ssh/auth* ~root/.ssh
#        sudo -i
#        cp /tmp/rpm.sh /root/
#        chmod 0777 /root/rpm.sh
#      SHELL
    end
  end
end