ENV['VAGRANT_SERVER_URL'] = 'http://vagrant.elab.pro'

MACHINES = {
  :r1 => {
    :box_name => "centos/7",
    :vm_name => "r1",
    :net => [
               ["10.0.0.1", 2, "255.255.255.0", "link1"],
               ["10.10.0.1", 3, "255.255.255.0", "link2"],
               ["10.10.10.11", 4, "255.255.255.0", "manag"],
            ]
  },
  :r2 => {
    :box_name => "centos/7",
    :vm_name => "r2",
    :net => [
               ["10.0.0.2", 2, "255.255.255.0", "link1"],
               ["10.20.0.2", 3, "255.255.255.0", "link3"],
               ["10.10.10.12", 4, "255.255.255.0", "manag"],  
            ]
  },
  :r3 => {
    :box_name => "centos/7",
    :vm_name => "r3",
    :net => [
               ["10.10.0.2", 2, "255.255.255.0", "link2"],
               ["10.20.0.1", 3, "255.255.255.0", "link3"],
               ["10.10.10.13", 4, "255.255.255.0", "manag"],
            ]
  },
}

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
    v.memory = 256
    v.cpus = 1
  end

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |config|
        config.vm.box = boxconfig[:box_name]
        config.vm.host_name = boxname.to_s
        
        boxconfig[:net].each do |ipconf|
            config.vm.network("private_network", ip: ipconf[0], adapter: ipconf[1], netmask: ipconf[2], virtualbox__intnet: ipconf[3])
        end
        
      config.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh
            cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i 's/^PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
            sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
            sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
            systemctl restart sshd.service
      SHELL

      config.vm.provision "ospf", type:'ansible' do |ansible|
        ansible.inventory_path = './inventories/all.yml'
        ansible.playbook = './playbooks/ospf.yml'
      end
    end
  end
end