ENV['VAGRANT_SERVER_URL'] = 'http://vagrant.elab.pro'

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
    v.memory = 256
  end

  config.vm.define "inetRouter" do |inetRouter|
    inetRouter.vm.network "private_network", ip: "192.168.50.4", virtualbox__intnet: "router-net", auto_config: false
    inetRouter.vm.network "private_network", ip: "192.168.50.5", virtualbox__intnet: "router-net", auto_config: false
    #management network
    inetRouter.vm.network "private_network", ip: "192.168.56.10"
    inetRouter.vm.hostname = "inetRouter"
  end

  config.vm.define "centralRouter" do |centralRouter|
    centralRouter.vm.network "private_network", ip: "192.168.50.6", virtualbox__intnet: "router-net", auto_config: false
    centralRouter.vm.network "private_network", ip: "192.168.50.7", virtualbox__intnet: "router-net", auto_config: false
    centralRouter.vm.network "private_network", ip: "192.168.2.1", virtualbox__intnet: "test-lan"
    #management network
    centralRouter.vm.network "private_network", ip: "192.168.56.11"
    centralRouter.vm.hostname = "centralRouter"
  end

  config.vm.define "testServer1" do |testServer1|
    testServer1.vm.network "private_network", ip: "192.168.2.2", virtualbox__intnet: "test-lan"
    #management network
    testServer1.vm.network "private_network", ip: "192.168.56.20"
    testServer1.vm.hostname = "testServer1"
  end

  config.vm.define "testClient1" do |testClient1|
    testClient1.vm.network "private_network", ip: "192.168.2.3", virtualbox__intnet: "test-lan"
    #management network
    testClient1.vm.network "private_network", ip: "192.168.56.21"
    testClient1.vm.hostname = "testClient1"
  end

  config.vm.define "testServer2" do |testServer2|
    testServer2.vm.network "private_network", ip: "192.168.2.4", virtualbox__intnet: "test-lan"
    #management network
    testServer2.vm.network "private_network", ip: "192.168.56.30"
    testServer2.vm.hostname = "testServer2"
  end

  config.vm.define "testClient2" do |testClient2|
    testClient2.vm.network "private_network", ip: "192.168.2.5", virtualbox__intnet: "test-lan"
    #management network
    testClient2.vm.network "private_network", ip: "192.168.56.31"
    testClient2.vm.hostname = "testClient2"
  config.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
        sed -i 's/^PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
        sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
        systemctl restart sshd.service
      SHELL

#    testClient2.vm.provision "vlan-bonding", type:'ansible' do |ansible|
#      ansible.limit = 'all'
#      ansible.inventory_path = './inventories/all.yml'
#      ansible.playbook = './vlan-bonding.yml'
#    end

  end

end