ENV['VAGRANT_SERVER_URL'] = 'http://vagrant.elab.pro'

MACHINES = {
:inetRouter => {
      :box_name => "centos/7",
      :vm_name => "inetRouter",
      #:public => {:ip => '10.10.10.1', :adapter => 1},
      :net => [
                #ip, adpter, netmask, virtualbox__intnet
                ["192.168.255.1", 2, "255.255.255.252",  "router-net"], 
              ]
},
:centralRouter => {
      :box_name => "centos/7",
      :vm_name => "centralRouter",
      :net => [
                ["192.168.255.2",  2, "255.255.255.252",  "router-net"],
                ["192.168.0.1",    3, "255.255.255.240",  "central-net"],
                ["192.168.0.33",   4, "255.255.255.240",  "hw-net"],
                ["192.168.0.65",   5, "255.255.255.192",  "mgt-net"],
              ]
},
:centralServer => {
      :box_name => "centos/7",
      :vm_name => "centralServer",
      :net => [
                ["192.168.0.2",    2, "255.255.255.240",  "central-net"],
              ]
},
:office1Router => {
      :box_name => "centos/7",
      :vm_name => "office1Router",
      :net => [
                ["192.168.0.3",     2,  "255.255.255.252",  "central-net"],
                ["192.168.2.1",     3,  "255.255.255.192",  "local1-net"],
                ["192.168.2.65",    4,  "255.255.255.192",  "testservers1-net"],
                ["192.168.2.129",   5,  "255.255.255.192",  "managers1-net"],
                ["192.168.2.193",   6,  "255.255.255.192",  "hardware1-net"],
              ]
},
:office1Server => {
      :box_name => "centos/7",
      :vm_name => "office1Server",
      :net => [
                ["192.168.2.2",  2,  "255.255.255.128",  "local1-net"],
              ]
},
:office2Router => {
      :box_name => "centos/7",
      :vm_name => "office2Router",
      :net => [
                ["192.168.0.4",    2,  "255.255.255.128",  "central-net"],
                ["192.168.1.1",    3,  "255.255.255.128",  "local2-net"],
                ["192.168.1.129",  4,  "255.255.255.192",  "testservers2-net"],
                ["192.168.1.193",  5,  "255.255.255.192",  "hardware2-net"],
              ]
}, 
:office2Server => {
      :box_name => "centos/7",
      :vm_name => "office2Server",
      :net => [
                ["192.168.1.2",    2,  "255.255.255.128",  "local2-net"],
              ]
},
  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        box.vm.provider "virtualbox" do |v|
        v.memory = 768
        v.cpus = 1
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network("private_network", ip: ipconf[0], adapter: ipconf[1], netmask: ipconf[2], virtualbox__intnet: ipconf[3])
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "inetRouter"
          box.vm.provision "shell", 
            name: "inetRouter",
            path: "inetRouter.sh"

        when "centralRouter"
          box.vm.provision "shell", 
            name: "centralRouter",
            path: "centralRouter.sh"

        when "centralServer"
          box.vm.provision "shell", 
            name: "centralServer",
            path: "centralServer.sh"

        when "office1Router"
          box.vm.provision "shell", 
            name: "office1Router",
            path: "office1Router.sh"

        when "office1Server"
          box.vm.provision "shell",
            name: "office1Server",
            path: "office1Server.sh"

        when "office2Router"
          box.vm.provision "shell",
            name: "office2Router",
            path: "office2Router.sh"

        when "office2Server"
          box.vm.provision "shell",
            name: "office2Server",
            path: "office2Server.sh"
        end
      end
  end
end